#!/bin/bash
# 
# Date : 2020.10.05
# 목적 : 라이브CD 관련 내용 수정
# 

# 절대경로로 변경
export WORK_PATH=$(cat ../conf/hamonikr.conf | grep work_path | awk -F 'work_path:' '{print $2}')


# job in initrd-tmp ============================================
cd $WORK_PATH/custom-img/extract-cd/casper/initrd-tmp
sudo lzma -dc -S .lz $WORK_PATH/custom-img/extract-cd/casper/initrd.lz | sudo cpio -id

cp -r $WORK_PATH/resource/extract-cd/casper/initrd-tmp $WORK_PATH/custom-img/extract-cd/casper/

sudo chmod 777 $WORK_PATH/custom-img/extract-cd/casper/initrd-tmp
sudo find . | sudo cpio --quiet --dereference -o -H newc | lzma -7 > new-initrd.lz
sudo chmod 777 new-initrd.lz
#sudo mv ../initrd.lz ../initrd.lz.ord
sudo rm -fr $WORK_PATH/custom-img/extract-cd/casper/initrd.lz
sudo cp ./new-initrd.lz $WORK_PATH/custom-img/extract-cd/casper/initrd.lz
cd $WORK_PATH/custom-img/extract-cd/casper
sudo rm -fr initrd-tmp
