#!/bin/bash
# 
# Date : 2020.10.20
# 목적 : HamoniKR 4.0 시스템 패키지 인스톨

# change fast apt mirror in korea
sed -i 's/packages.linuxmint.com/mirrors.evowise.com\/linuxmint\/packages/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/kr.archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/extras.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list

# 하모니카 저장소 추가
curl -sL https://pkg.hamonikr.org/add-hamonikr-jin.apt | sudo -E bash -

#sudo apt-get upgrade -y

sudo apt-get install -y hamonikr-system-settings

# 데스크톱 환경
sudo apt-get install -y hamonikr-desktop-environment

# 하모니카 테마팩
sudo apt-get install -y hamonikr-themes

# 하모니카 아이콘팩
sudo apt-get install -y hamonikr-jin-icon-theme

# 라이브 부팅 CD 설치 인스톨러에 나오는 슬라이드 쇼
sudo apt-get install -y ubiquity-slideshow-mint

# 님프 관련 설정
im-config -n nimf
# 라이브시디에서 한글키보드를 사용하려면 nimf 설정의 XKB 옵션 중 Hangule 키를 Right Alt 사용으로 체크
# sed -i "s/\[''\]/\['korean:ralt_rctrl'\]/g" /usr/share/glib-2.0/schemas/org.nimf.settings.gschema.xml

# 온보드
sudo apt-get install -y hamonikr-onboard-layout-ko

# 한글 언어팩 설치
sudo apt-get install -y language-pack-ko
# 한글 언어팩 설정(/etc/default/locale)
#sudo update-locale
