#!/bin/bash
# 
# Date : 2020.10.20
# 목적 : HamoniKR 4.0 시스템 패키지 인스톨

echo "\033[32m"'--------------------------------------'"\033[0m"
echo "\033[32m"' 하모니카 시스템에 필요한 패키지 인스톨 '"\033[0m"
echo "\033[32m"'--------------------------------------'"\033[0m"

# change fast apt mirror in korea
sed -i 's/packages.linuxmint.com/ftp.kaist.ac.kr\/linuxmint/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/kr.archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list
sed -i 's/extras.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list.d/official-package-repositories.list

# 하모니카 저장소 추가 (저장소가 추가될 때 apt update 됨)
curl -sL https://pkg.hamonikr.org/add-hamonikr-jin.apt | sudo -E bash -

echo "\033[32m"'-------------------'"\033[0m"
echo "\033[32m"' 최신버전 커널 설치 '"\033[0m"
echo "\033[32m"'-------------------'"\033[0m"

# 최신 커널 설치
sudo apt-get --only-upgrade install -y linux-image-generic

# 이전 커널 제거(추후 작업시 버전 변경이 필요할 수 있습니다.)
sudo apt-get --purge remove -y linux-image-5.4.0-26-generic
sudo apt-get --purge remove -y linux-headers-5.4.0-26
sudo apt-get --purge remove -y linux-headers-5.4.0-26-generic
sudo apt-get --purge remove -y linux-modules-5.4.0-26-generic
sudo apt-get --purge remove -y linux-modules-extra-5.4.0-26-generic

echo "\033[32m"'---------------------------------------------------'"\033[0m"
echo "\033[32m"' 최신 커널 설치 완료 '"\033[0m"
echo "\033[32m"' livecd 커널 변경은 chroot작업이 끝나고 이루어집니다. '"\033[0m"
echo "\033[32m"'---------------------------------------------------'"\033[0m"
# ※ extract-cd > casper > vmlinuz는 chroot 작업이 끝나고 custom-img > edit > boot > vmlinuz-5.4.0-xx-generic 파일 복사
# ※ extract-cd > casper > initrd.lz는 chroot 작업이 끝나고 custom-img > edit > boot > initrd-5.4.0-xx-generic 파일 복사

sudo apt-get upgrade -y

# 하모니카 시스템 세팅
sudo apt-get install -y hamonikr-system-settings

# 데스크톱 환경
sudo apt-get install -y hamonikr-desktop-environment

# 하모니카 GRUB 테마
sudo apt-get install -y grub-theme-hamonikr-jin

# 하모니카 PLYMOUTH 테마
sudo apt-get install -y plymouth-theme-hamonikr

# 하모니카 아이콘팩
sudo apt-get install -y hamonikr-jin-icon-theme

# 라이브 부팅 CD 설치 인스톨러에 나오는 슬라이드 쇼
sudo apt-get install -y ubiquity-slideshow-mint

# 민트 리포트(하모니카 리포트)
sudo apt-get install -y mintreport

# Re-generator inside ISO image's repo(하모니카 키가 포함되어 있는 우분투 키링 패키지)
sudo apt install --reinstall -y -qqq ubuntu-keyring/jin

# 하모니카 바탕화면 UI 테마
sudo apt-get install -y hamonikr-themes

# 하모니카 nemo 세팅
sudo apt-get install -y hamonikr-nemo-actions

# 하모니카 카카오톡
sudo apt-get install -y hamonikr-kakaotalk