#!/bin/bash
# 
# Date : 2020.10.20
# 목적 : HamoniKR 4.0 시스템 패키지 인스톨

# 하모니카 저장소 추가
curl -sL https://pkg.hamonikr.org/add-hamonikr-jin.apt | sudo -E bash -

#sudo apt-get upgrade -y

sudo apt-get install -y hamonikr-system-settings


sudo apt-get install -y hamonikr-desktop-environment


# 라이브 부팅 CD 설치 인스톨러에 나오는 슬라이드 쇼
sudo apt-get install -y ubiquity-slideshow-mint

# 하모니카 아이콘 팩이 들어있는 민트X아이콘으로 아이콘 관련 설정시 설치되어 있어야 한다.
sudo apt-get install -y mint-x-icons

# 님프 관련 설정
im-config -n nimf
# 라이브시디에서 한글키보드를 사용하려면 nimf 설정의 XKB 옵션 중 Hangule 키를 Right Alt 사용으로 체크
# sed -i "s/\[''\]/\['korean:ralt_rctrl'\]/g" /usr/share/glib-2.0/schemas/org.nimf.settings.gschema.xml

# 온보드
sudo apt-get install -y hamonikr-onboard-layout-ko


# 언어팩 설치
sudo apt-get install -y language-pack-ko
# 언어팩 설정
sudo update-locale
