#!/bin/bash
# 
# Date : 2020.10.22
# 목적 : HamoniKR 4.0 iso 빌드전 clean
#

export chroot_workpath='/deb'
export chroot_after_rss='/deb/install_after'

sudo dpkg --configure -a ; \
sudo apt autoremove -y; \
sudo apt-get install -f

# copy files after install
sudo cp -r $chroot_after_rss/* /

# update n clean
sudo apt-get update
sudo apt-get clean


# delete resource directory
sudo rm -rf /script
sudo rm -rf /deb
sudo rm -rf /edit
